## ğŸ“¦ HatalarÄ± Boxâ€™lama (boxing errors)

Orijinal hatalarÄ± korurken **basit kod yazmanÄ±n** bir yolu, hatalarÄ± `Box` iÃ§ine koymaktÄ±r. Bunun dezavantajÄ±, altta yatan hata tÃ¼rÃ¼nÃ¼n **sadece Ã§alÄ±ÅŸma zamanÄ±nda** bilinmesi ve **statik olarak belirlenememesidir**.

`stdlib`, `Box` tÃ¼rÃ¼nÃ¼n, `Error` traitâ€™ini uygulayan herhangi bir tÃ¼rden `Box<Error>` trait nesnesine dÃ¶nÃ¼ÅŸÃ¼mÃ¼ `From` aracÄ±lÄ±ÄŸÄ±yla desteklemesi sayesinde hatalarÄ± boxâ€™lamamÄ±za yardÄ±mcÄ± olur.

```rust
use std::error;
use std::fmt;

// Alias'Ä± `Box<dyn error::Error>` kullanacak ÅŸekilde deÄŸiÅŸtiriyoruz.
type Result<T> = std::result::Result<T, Box<dyn error::Error>>;

#[derive(Debug, Clone)]
struct EmptyVec;

impl fmt::Display for EmptyVec {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "invalid first item to double")
    }
}

impl error::Error for EmptyVec {}

fn double_first(vec: Vec<&str>) -> Result<i32> {
    vec.first()
        .ok_or_else(|| EmptyVec.into()) // Box'a dÃ¶nÃ¼ÅŸtÃ¼rÃ¼lÃ¼yor
        .and_then(|s| {
            s.parse::<i32>()
                .map_err(|e| e.into()) // Box'a dÃ¶nÃ¼ÅŸtÃ¼rÃ¼lÃ¼yor
                .map(|i| 2 * i)
        })
}

fn print(result: Result<i32>) {
    match result {
        Ok(n) => println!("The first doubled is {}", n),
        Err(e) => println!("Error: {}", e),
    }
}

fn main() {
    let numbers = vec!["42", "93", "18"];
    let empty = vec![];
    let strings = vec!["tofu", "93", "18"];

    print(double_first(numbers));
    print(double_first(empty));
    print(double_first(strings));
}
```
